### ISSUE TITLE
[to be discussed] implementation of saneURL via brainscapes api

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#10]
Currently, brainscapes explorer backend implements a saneURL feature (which is effectively a URL shortener). The requirement for this service is:

- if user is anonymous, the link should expire after set period of time (I think it is currently set to 72 hrs)
- if user is logged in, the link should persist forever (we could consider allowing authenticated user to manage their own created links in the future)
- anyone (logged in or not) should be able to be redirected via valid links
- throttling is enabled to ensure that the feature is not abused

If brainscapes explorer is to go truly backendless, we will need to consider how this feature will be implmented in brainscapes api.

---------- old comments ---------
 Gui, Xiaoyun 

@v.marcenko currently, we use object storage on cscs (I have acquired a username and password for this purpose since a time ago) to store the json files. We are constrained by the limitations that:

- links needs to be valid to both logged in and anonymous users (so it cannot be stored on the user space, e.g. user seafile)

- links needs to persist, and work across dev and prod instances (this mostly rules out mounted volumes and provisioned databases)

As far as sane url is concerned (i.e. may not apply to caching), these are , IMO, the possible options

- cscs storage (per current solution)
- seafile storage of a specific collab/wiki (probably most feasible)
- KG private (name)space / domain (still not sure if this is a thing)

---
Gui, Xiaoyun

It just occurred to me, the data proxy developed by EPFL should allow cscs storage to be used with ebrains iam oidc jwt token.

It could be the best of both worlds

**Comment by xgui3783** [comment]
not planned, as this is siibra-explorer specific feature
