### ISSUE TITLE
Parcellation features returning incorrect data 

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-api#100]
`/atlases/{atlas_id}/parcellations/{parcellation_id}/features` endpoint does not return data correctly. `description`, `dataset_id`, and other fields are not included on the returned json, but they are inside the `name` field which looks like this:
```
name: "... {'name': '...', 'dataset_id': '...', 'description': '...', 'citation': '...', 'authors': [...], 'cohort': '...', 'subject': '...', 'filename': '...'}"
```

`...` - is filled with relevant data

**Comment by fsdavid** [comment]
Great. We need `description`. For now, not sure if we need `citation` and `authors` separately, but would be nice to have them as part of the description.

**Comment by xgui3783** [comment]
we will see what we can do. 

Not a promise, but we will look into if it is resource intensive to retrieve some/all of the aforementioned fields.

**Comment by xgui3783** [comment]
should be fixed. e.g.:

```sh
curl -X 'GET'   'https://siibra-api-dev.apps-dev.hbp.eu/v2_0/atlases/human/parcellations/2.9/features?page=1&size=1'   -H 'accept: application/json'  | jq '.items[0] | keys'
```

returns 
```json
[
  "@id",
  "@type",
  "authors",
  "citation",
  "cohort",
  "columns",
  "dataset_id",
  "description",
  "filename",
  "matrix",
  "name",
  "parcellations",
  "subject"
]

```
