### ISSUE TITLE
Deliver connectivity matrices through feature endpoint

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-api#108]
The [connectivity matrix endpoint](https://siibra-api-latest.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290/features/ConnectivityMatrix) does only deliver basic metadata. It needs to deliver the data object as well.

**Comment by xgui3783** [comment]
it does. 

e.g. [/endpoint/src_name](https://siibra-api-latest.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290/features/ConnectivityMatrix/Average%20streamline%20counts%20from%20diffusion%20imaging%2C%201000BRAINS%20cohort)

**Comment by xgui3783** [comment]
it does

e.g.

```sh
curl 'https://siibra-api-rc.apps.hbp.eu/v3_0/feature/RegionalConnectivity/cf375741057a19d172517b719cc12e59--7ec2f0bd8fb0437d8195172556f1417c?parcellation_id=minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290&subject=000&type=FunctionalConnectivity'
```
