### ISSUE TITLE
The connectivity matrix should not depend on the parcellation region.

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#11]
The connectivity matrix function should return full connectivity of the parcellation and should not be connected to specific regions.
Currently to get data we need an endpoint: `/atlases/{atlas_id}/parcellations/{parcellation_id}/regions/{region_id}/features`

**Comment by xgui3783** [comment]
in `siibra-python`, there now exist the concept of `GlobalFeature` and `RegionalFeature`. 

I feel `/atlases/{atlas_id}/parcellations/{parcellation_id}/regions/{region_id}/features` should still exist for `RegionalFeature`, but connectivity matrix would be a `GlobalFeature`, which can be attributable to a parcellation

I propose we add 

`/atlases/{atlas_id}/parcellations/{parcellation_id}/features`

to query global features and

`/atlases/{atlas_id}/parcellations/{parcellation_id}/features/{modality}`

to return global features. 

Would love to get your opinion @marcenko

**Comment by xgui3783** [comment]
fixed by #20
