### ISSUE TITLE
Remove unnecessary parameters

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-api#113]
Endpoints typically require a redundant set of parameters, like atlas id / parcellation id / region id. In most cases, some parameters can be safely removed. For example, if a parcellatino id is provided, it is unnecessary to provide an atlas id, since the atlas is uniquely defined through the parcellation.

**Comment by xgui3783** [comment]
solved by v3 refactor (adapting to siibra v0.4)
