### ISSUE TITLE
deprecation of kg v1 results in numerous v1/v2 endpoints returning 500 error

### ISSUE THREAD

**Issue by valentin-pinkau** [FZJ-INM1-BDA/siibra-api#123]
https://siibra-api-stable.apps.hbp.eu/v1_0/atlases/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F522b368e-49a3-49fa-88d3-0870a307974a/parcellations returns a 500 error.

**Comment by xgui3783** [comment]
should be fixed by https://github.com/FZJ-INM1-BDA/siibra-api/commit/2791148011a31cd7864e524d07e1bc1d07e67db0 

Feel free to reopen ticket/open new ticket if other endpoints are found.
