### ISSUE TITLE
Parcellation is not a tree as it contains a cycle

### ISSUE THREAD

**Issue by valentin-pinkau** [FZJ-INM1-BDA/siibra-api#124]
https://siibra-api-stable.apps.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290/regions
![Screenshot 2023-03-16 at 14 41 53](https://user-images.githubusercontent.com/2582395/232996684-82f525d7-2373-4bc2-a3ec-3c4d63382c0b.png)

**Comment by xgui3783** [comment]
this is an issue on ontology data

e.g. https://search.kg.ebrains.eu/?category=Dataset&q=julich%20brain%202.9#a8932c7e-063c-4131-ab96-996d843998e9

in julichbrain-ontology_29.0.json

the nested "overall"s exist.

Through the discussion with @dickscheid , we will fix it on siibra-python side

**Comment by xgui3783** [comment]
related: relevant bug siibra configuration : https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/siibra-0.4a46/parcellations/julichbrain_v2_9_0.json#L2508-2513

relevant issue on siibra-configuration: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/10

**Comment by xgui3783** [comment]
This issue has actually been solved by https://github.com/FZJ-INM1-BDA/siibra-api/commit/2791148011a31cd7864e524d07e1bc1d07e67db0 and https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/commit/6a47c89152a06442ab3c660bb93e8d0dfc4411ec

and deployed.

see 

```
curl https://siibra-api-stable.apps.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290/regions | jq | grep 'overall'
```
