### ISSUE TITLE
Explore region in other different spaces

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#13]
Could we get info about the region, available in different template spaces?
Something like:

`{ name: "region 1", availableIn: [ Bigbrain..., MNI 152...] }`

**Comment by marcenko** [comment]
@dickscheid 
In siibra-python parcellations have a method: `supports_space`. Can I assume that if a parcellation supports a space, than the region in the selected parcellation is also available in that supported space?

**Comment by dickscheid** [comment]
It depends what you mean by „also supported“. I would agree that the region will have a mask defined there, at least as part of the main parcellation map, but I do not rigorously check this! (we probably should!)

However, it does not necessarily imply that the region has a „regional map“, e.g. an indvidual file beyond the main parcellation map, like a probability map.

**Comment by marcenko** [comment]
@fsdavid 
What exactlly do you mean by `availableIn`?

**Comment by fsdavid** [comment]
@marcenko 
I wanted to edit the issue text but I have not right to do this. So I'll comment:
In Siibra explorer, when the user selects a region, he/she will be able to explore region features, connectivity, etc., and also find if the selected region is also available in other templates. E. g. if users select `Area TE 3 (STG)` in `ICBM 152` on the sidebar, they will see that the current region also exists in `Big brain`

**Comment by dickscheid** [comment]
Dear all, to clarify this, for this request is it sufficient to have the area indexed in the standard parcellation map, so the `supports_space` method should be the way to go. We should however introduce a test on parcellation construction, that this will always be defined. It can curently be assumed, but it is not technically enforced by the framework. I suggest opening an issue to include this in a future release of siibra-python.

**Comment by marcenko** [comment]
@fsdavid Could you have a look at how it is implemented now? Each region has a field `availableIn`. Is this what you meant?
Even if the information is not 100% correct, we can get clear on the structure and will not need to much changes, when we implement the indexed area part.

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions`

**Comment by fsdavid** [comment]
@marcenko Nice update, it should work.

**Comment by fsdavid** [comment]
Could we return more details about the regions inside available templates? E.g. Id, name, position?

**Comment by marcenko** [comment]
Could you give a short JSON example how you mean it? I do not yet understand where the details should be added.

**Comment by fsdavid** [comment]
I'm not sure exactly how it could be retrieved but, I mean to include template specific data of the region into the list for example:
region - `Area TE 3 (STG)` exists in `BigBrain`, so we need the data like
` {`
`    ...region,`
`    availableIn: {`
`        id: 'minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2',`
`       name: 'MNI152 2009c nonl asym',`
`        region: {`
`            name: '',`
`            children: [`
`                {name: 'Area TE 3 (STG) left', position: [1,1,1]} `
`                {name: 'Area TE 3 (STG) right', position: [2,2,2]} `
`]}}}`

**Comment by xgui3783** [comment]
I should say, in lieu with `volumeSrc` attribute, perhaps it could look something like:

```
{
  "availableIn": {
    "minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2": [{
        "name": "hoc1 - right"
    }, {
        "name": "hoc1 - left"
    }]
  }
}
```

**Comment by fsdavid** [comment]
To be more concrete:

When we are fetching region data from an endpoint: 
https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions

We are getting a list of regions containing the list of the templates where these regions are available. The variable name is `availableIn`

So the result looks like this:

```json
{
  ...Region details
  availableIn: [
    {
         "id": "minds/core/referencespace/v1.0.0/a1655b99-82f1-420f-a3c2-fe80fd4c8588",
         "name": "Big Brain"
    }, 
    {
         "id": "minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2",
         "name": "MNI152 2009c nonl asym"
    }
]
}```


As you see we have `id` and `name` for templates, but we would like to get more details of the region inside each `availableIn` template. So it would like: `Region` -> `AvailableIn Templates array` -> `Regions Array`.
It would be useful when we are fetching regions from `BigBrain`. Use case in Siibra explorer looks like - If we select `Bigbrain` and we are trying to find available templates of `Area STS1 (STS)` (`Explore in other templates`) - with current API we will get just `mni152`, but we need `mni152 - left hemisphere` and `mni152 - right hemisphere`.

So expected result looks like:
```json
{
  ...Region details
  "availableIn": {
    name: "MNI152 2009c nonl asym",
    id: "minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2",
    "regions": [{
      "name": "hoc1 - right",
    }, {
      "name": "hoc1 - left",
    }
   ]
  }
}
 ```

@xgui3783 I've changed your version a little bit (from your last comment) because I think we need to have the name of the template here.

**Comment by xgui3783** [comment]
> I've changed your version a little bit (from your last comment) because I think we need to have the name of the template here.

with id, we can get the name.

I just think the interface should be more unified, when dealing with an attribute, which are separated in terms of reference space, and then in terms of hemisphere.

**Comment by fsdavid** [comment]
I was just thinking about the future where we will fetch template data more dynamically, but if we will anyways have fetched template names then `id` would be enough.

**Comment by xgui3783** [comment]
> I was just thinking about the future where we will fetch template data more dynamically, but if we will anyways have fetched template names then `id` would be enough.

more reasons to require id, no? since it will be used to fetch template info

**Comment by xgui3783** [comment]
this is now supported via `regions/{region_id}/related` query
