### ISSUE TITLE
Make sure siibra-api fail gracefully if KG is down and data is not cached.

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-api#15]
relevant trello card: https://trello.com/c/qMbrbBPX/66-make-sure-all-components-fail-gracefully-if-kg-is-down-and-data-is-not-cached

**Comment by marcenko** [comment]
This Issue is very important.
Especially after today. KG still responses with HTTP 500.

We need to make siibra more resilient in such cases.
