### ISSUE TITLE
Get Ebrains Knowledge Graph Id with connectivity profile

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-api#21]
Could we get a KG id while fetching the connectivity profiles?

With the endpoint:
https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F5151ab8f-d8cb-4e67-a449-afe2a41fb007/features/ConnectivityProfile

we are fetching available connectivity profiles on a specific region. Could we also include `kgschema/kgid` attribute for each profile where it is available?
For example, connectivity profile `1000BRAINS study, connectivity data` should be connected to this dataset: https://search.kg.ebrains.eu/instances/Dataset/e428cb6b-0110-4205-94ac-533ca5de6bb5

**Comment by marcenko** [comment]
As far as I see we only have kg information for one profile:
`https://jugit.fz-juelich.de/t.dickscheid/brainscapes-datafeatures/-/blob/master/1000brains.json`

Does someone know if the other ConnectivityProfiles have an KG Id? @FZJ-INM1-BDA/siibra-team

**Comment by dickscheid** [comment]
The others are from the dataset of Oleksandr Popovych, I think it is this one: https://search.kg.ebrains.eu/instances/Dataset/50c215bc-4c65-4f11-a4cd-98cc92750977

You could add this to the json file, but please verify that the files are the same.

Please be careful with the wording: each of these dataset files is a connectivity  matrix, mapping all regions of the parcellation to all others. A profile is one row of the ,atria, mapping to one particular region connection strengths of all others.

**Comment by marcenko** [comment]
@fsdavid 
KgId is now included, at least where Id and schema is present in the data. 

see:
`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F5151ab8f-d8cb-4e67-a449-afe2a41fb007/features/ConnectivityProfile`
