### ISSUE TITLE
Getting incorrect datasets while fetching connectivity in Cytoarchitectonic maps

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-api#23]
I'm trying to fetch connectivity for `Cytoarchitectonic maps v2.6` with URL:
[https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile](https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile)

I'm getting datasets of `Cytoarchitectonic maps V1.8` - you can check it with dataset name which contains `184` in the name - e. g. `Averaged_FC_JuBrain_184Regions_HCP_REST_FIX_AVER_MEAN`. It should contain `248` instead of `184` e. g. `Averaged_FC_JuBrain_246Regions_HCP_REST_FIX_AVER_MEAN`. 

I guess that is a reason why, it is not possible to fetch data for `Cytoarchitectonic maps v1.8`

**Comment by xgui3783** [comment]
I suspect it is simply a misname of the datasets (possibly related to https://jugit.fz-juelich.de/t.dickscheid/brainscapes-datafeatures/-/issues/1)

e.g.

```sh
> curl https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile/Averaged_SC_JuBrain_184Regions_eNKI_10M_length_MEAN | jq '.__column_names | length'
244
```

**Comment by fsdavid** [comment]
> I suspect it is simply a misname of the datasets (possibly related to https://jugit.fz-juelich.de/t.dickscheid/brainscapes-datafeatures/-/issues/1)
> 
> e.g.
> 
> ```shell
> > curl https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile/Averaged_SC_JuBrain_184Regions_eNKI_10M_length_MEAN | jq '.__column_names | length'
> 244
> ```


@xgui3783 Then I'll create a new issue for `I guess that is a reason why it is not possible to fetch data for Cytoarchitectonic maps v1.8`

**Comment by marcenko** [comment]
@fsdavid 
Could you check if the result is now correct. 
It seems to me, that this bug is fixed.

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile`
