### ISSUE TITLE
Cannot fetch connectivity profile for Julich brain Cytoarchitectonic maps v1.8

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-api#25]
Cannot fetch connectivity profile for Julich brain Cytoarchitectonic maps v1.8. endpoint returns `error 500`

https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F8/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile

**Comment by xgui3783** [comment]
I cannot find reference to `juelich/iav/atlas/v1.0.0/8` , where did you get the parc id `juelich/iav/atlas/v1.0.0/8` ?

**Comment by xgui3783** [comment]
admittedly, error message could be clearer

**Comment by marcenko** [comment]
If you now do a request for a wrong parcellation you get:

`"The requested parcellation is not supported by the selected atlas."`

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F8/regions/minds%2Fcore%2Fparcellationregion%2Fv1.0.0%2F18e5e1b0-6c25-4f55-a967-0834d2bd3ee4/features/ConnectivityProfile`

Since this was not about connectivity but about wrong parcellations is this issue done?

**Comment by fsdavid** [comment]
@marcenko I'm trying to fetch connectivity for the `Julich brain V1.18` region - `Area TE 3 (STG) right`. From the API I'm getting an empty array.
URL: https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/features/ConnectivityProfile

I've tested and it works on the Siibra python side. you can find an example here: https://colab.research.google.com/drive/1yEB1eYQeqrmidYje7XExbrHprConszs8?usp=sharing

**Comment by xgui3783** [comment]
It's probably more useful to test on an endpoint vadim is familiar with. 

same call to:

- https://siibra.apps-dev.hbp.eu returns {"detail":"No method yet for connectivity profile"}
- https://siibra-api-master.apps-dev.hbp.eu returns Internal server error. In log: `AttributeError: 'ConnectivityProfile' object has no attribute 'kg_schema'`

**Comment by fsdavid** [comment]
From Xiao's comment, I can imagine that problem is caused by the region's `id` field. As not all regions have `id`, we are using the `name`. I think API is expecting to receive an `id` instead of the `name`.

**Comment by marcenko** [comment]
That's right. At the moment the feature endpoint requires an `id`. I can extend the endpoint to accept both `id` and `name`.
As it works in:

`https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/`

**Comment by xgui3783** [comment]
> From Xiao's comment, I can imagine that problem is caused by the region's `id` field. As not all regions have `id`, we are using the `name`. I think API is expecting to receive an `id` instead of the `name`.

This is inaccurate. 

for example

```
curl 'https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/features/EbrainsRegionalDataset' 
```

works... (although a bit slow)

**Comment by fsdavid** [comment]
> > From Xiao's comment, I can imagine that problem is caused by the region's `id` field. As not all regions have `id`, we are using the `name`. I think API is expecting to receive an `id` instead of the `name`.
> 
> This is inaccurate.
> 
> for example
> 
> ```
> curl 'https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/features/EbrainsRegionalDataset' 
> ```
> 
> works... (although a bit slow)

Sorry, couldn't understand what do you mean?

**Comment by fsdavid** [comment]
> That's right. At the moment the feature endpoint requires an `id`. I can extend the endpoint to accept both `id` and `name`.
> As it works in:
> 
> `https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/`

Nice, I think it should fix the problem.

**Comment by xgui3783** [comment]
> > > From Xiao's comment, I can imagine that problem is caused by the region's `id` field. As not all regions have `id`, we are using the `name`. I think API is expecting to receive an `id` instead of the `name`.
> > 
> > 
> > This is inaccurate.
> > for example
> > ```
> > curl 'https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/features/EbrainsRegionalDataset' 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works... (although a bit slow)
> 
> Sorry, couldn't understand what do you mean?

in `regions/${region_id}` region_id can either be id, or fuzzy term such as `hoc1 left`

**Comment by xgui3783** [comment]
> That's right. At the moment the feature endpoint requires an `id`. I can extend the endpoint to accept both `id` and `name`.
> As it works in:
> 
> `https://siibra-api-tmpfullvolmetadata.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/`

Hmm, I this looks exactly like the offending URL, without the trailing `features/ConnectivityProfile` ?

**Comment by fsdavid** [comment]
> in `regions/${region_id}` region_id can either be id, or fuzzy term such as `hoc1 left`

Yeah, that's true but this logic does not work for connectivity.

**Comment by xgui3783** [comment]
> > in `regions/${region_id}` region_id can either be id, or fuzzy term such as `hoc1 left`
> 
> Yeah, that's true but this logic does not work for connectivity.

I agree it doesn't work, but, IMO, using region_id vs region_name is not the core issue.

**Comment by marcenko** [comment]
I found the problem and it works now.
It was my bad, I used the kgSchema und kgId, which will only be available with the next siibra-python release.

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20TE%203%20(STG)%20right/features/ConnectivityProfile`

**Comment by fsdavid** [comment]
@marcenko Could you please check this endpoint? it's buggy and returns a lot of profiles:

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20PF%20(IPL)%20right/features/ConnectivityProfile`

**Comment by marcenko** [comment]
@fsdavid 

The profiles are from:
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-datafeatures

Could you explain, what the expected result would be?

**Comment by xgui3783** [comment]
> @marcenko Could you please check this endpoint? it's buggy and returns a lot of profiles:
> 
> `https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20PF%20(IPL)%20right/features/ConnectivityProfile`

```sh
curl 'https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20PF%20(IPL)%20right/features/ConnectivityProfile' | jq 'length'
# returns 8
```
which seems to be the expected result, judging from the data feature repository? So it is behaving normally?

**Comment by fsdavid** [comment]
Now it definitely returned 8. It was hundreds when I tested but now I'm getting `CORS error`. 
URL: `https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20PF%20(IPL)%20right/features/ConnectivityProfile/Average%20streamline%20counts%20from%20diffusion%20imaging%2C%201000BRAINS%20cohort`

![image](https://user-images.githubusercontent.com/26521731/123272979-8997a600-d502-11eb-8256-393341be193b.png)

It returns errors only for single region connectivity profiles. The connectivity matrix of full parcellation is loaded successfully.

**Comment by xgui3783** [comment]
Loads fine for me it seems?

**Comment by marcenko** [comment]
For me it loads fine aswell. I tested it yesterday and today.
There is also nothing CORS related in the logs.

**Comment by xgui3783** [comment]
Request payload.... Are you doing a post request rather than a get request @fsdavid ?

**Comment by fsdavid** [comment]
Yeah, you are right, I've missed `npm i` to update the connectivity component.

But there is another bug 😄 . Returned data is incorrect. Returned and stored data are different. 

Data in Jugit:
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-datafeatures/-/blob/master/1000brains.json#L332

Returned data:
https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions/Area%20PF%20(IPL)%20right/features/ConnectivityProfile/Average%20streamline%20counts%20from%20diffusion%20imaging%2C%201000BRAINS%20cohort

**Comment by xgui3783** [comment]
Indeed, there was a bug.

I am aware of it, and already have a fix.

**Comment by fsdavid** [comment]
@xgui3783 nice let me know when the fix will be online and I will test the connectivity component. Hope, it will work.
