### ISSUE TITLE
[bug] shared instance of atlas results in race condition errorenous http responses

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-api#33]
It appears that individual atlases instance (human, rat, mouse) are shared in the same process.

This could (and has) led to difficult to decipher bugs, such as regions returned are not the one that's requested, or (as I found out the hard way) datasets requested did not belong to the region(s) requested.

min repro:

use https://github.com/FZJ-INM1-BDA/siibra-api/tree/bug_minrepro (slightly modified to magnify the effect of network latency / multiple concurrent users)

```sh
#! /bin/bash

# works correctly:

curl http://localhost:5000/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions | 
  jq '[.[].name]'

# expected output: 
#[
#  "telencephalon",
#  "metencephalon"
#]

sleep 1

# does not work

curl http://localhost:5000/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/regions | 
  jq '[.[].name]' & \
curl -o /dev/null \
  http://localhost:5000/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F6/regions

# actual output
# [
#   "Left Hemisphere",
#   "Right Hemisphere"
# ]

```

**Comment by marcenko** [comment]
In the first fix I create a separate atlas for each request.
It seems to work.
@xgui3783 I tried your script and get now the expected value. Do you have more cases where you experienced the issue and can do some test?

**Comment by xgui3783** [comment]
I believe this issue is addressed. Thanks.
