### ISSUE TITLE
Could not fetch connectivity matrixes

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-api#39]
Cannot fetch Connectivity matrixes for any profile. Getting an error:

```
 {
    "detail": "modality with name Average streamline counts from diffusion imaging, 1000BRAINS cohort not found"
} 
```

Actually connectivity matrix with the same name exists:

![image](https://user-images.githubusercontent.com/26521731/125976141-6cf4f0d2-1077-4a3d-8ae8-291f31c06173.png)

Testing URL: https://siibra-api-latest.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579/features/ConnectivityMatrix/Average%20streamline%20counts%20from%20diffusion%20imaging%2C%201000BRAINS%20cohort

**Comment by marcenko** [comment]
Fixed with the pydantic rewrite
