### ISSUE TITLE
gene endpoint response

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#5]
Create endpoints for:

GET /genes/ lists all gene symbol
GET /genes/{symbol}?region={region} return what it is returning now

**Comment by marcenko** [comment]
@xgui3783 @fsdavid 
Could you please have a look at this two URLs?
I did some adjusments. Seems like it does not work for each region, but I guess there is an error on siibra-python side.
At the moment if the error appears I catch it and return 404.

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/amygdala/features/GeneExpression?gene=GABARAPL2`

`https://siibra-api-master.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-25/regions/amygdala/features/GeneExpression/5bfde5a0b63efeae31cb40242f31a649?gene=GABARAPL2`

**Comment by xgui3783** [comment]
@marcenko did you fix the issue in the intrim? :p

I just had the opportunity to try the endpoints, and they are now working.

incidentally, I had an exchange with fabrice this morning, re deployment on okd-dev. apparently something went poo poo and all services hosted on okd-dev were mal functioning.

**Comment by xgui3783** [comment]
I would consider this issue resolved, unless you have other opinions? @marcenko @fsdavid
