### ISSUE TITLE
find objects by name

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#64]
At the moment we can access one single atlas/parcellation/space/region by id.

Since siibra-python has the feature of a fuzzy search, we could implement the same feature for siibra-api.

For example:

`.../parcellation/<par-id>/region?find=<region-name>`

This would search fuzzy by region name and either return a single region or a Bad Request Response if more than one region was found.

**Comment by xgui3783** [comment]
hmm, in fact the current `parcellation/<parc-id>/region/<region-id>` already performs the said fuzzy search (though not explicit in doc/rest pattern)

I would argue that the new endpoint `/region?find=<fuzzy-region-name>` should return a list of regions that matches the query?

**Comment by marcenko** [comment]
I actually thought we have the fuzzy search for region only until we have IDs for each region.

But you are right we could also return a list of all found regions. Would make more sence for a **find-feature**.
