### ISSUE TITLE
[feature request] an alternate way to query feature

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#7]
currently, there exists:

`/features`

which lists all features by name and

`/features/{modality_id}?region={region_name}`

which gets feature {modality_id} filtered by region

**request**

is it desirable to implement a reverse logic, e.g.

```
/region/{region_id}/features
/region/{region_id}/features/{modality_id}
```

hich allow brainscapes explorer to directly query which kind of modality does a region have

**use case**

it is far more frequent that user selects a region, and wish to see what kind of modality is available, and then explore regional modality.

**Comment by xgui3783** [comment]
I believe this issue is resolved. 

dev version of siibra-explorer already use `/atlas/{atlas_id}/parcellation/{parcellation_id}/region/{region_id}/feature/{feature_name}` to query receptor data

@marcenko do you think we can close this issue to reduce clutter?
