### ISSUE TITLE
feature request: given feature id able to return the detail of the feature

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-api#79]
currently, in order to get the detail of a feature, one must know the full context of the feature (atlas? parcellation? space? region?)

I propose an endpoint, e.g.

```
GET /features/{feature_id}?{query_params}
```

which would return the detail of the feature. additional context can be provided by `{query_param}`, in which case, it will be passed to the `to_model` method as kwargs.

**Comment by marcenko** [comment]
@xgui3783 When getting features from siibra-python an `atlas concept` is expected. Should this concept be one of the query params?

**Comment by xgui3783** [comment]
I was more thinking of no atlas-concept is required. 

I mean, feature_id should be unique, regardless of atlas concept, right?

some background, I would like to reenable the ability to pin datasets, and/or show datasets without the context (for url encoding and previewing datasets) for example.

**Comment by xgui3783** [comment]
in essence, we will have:

```
GET /features/{feature_id}
```

which will retrieve a specific id, regardless of context

the current `GET /features` perhaps should be remodelled into `GET /modalities`, which will return a list of valid modalities. These should also include a `type` in their key value pair. 

in all `GET /**/features` endpoints :

- all returned response should include `type` attribute (some do already, most don't)
- should allow for `type` optional query param, which allow the returned features to be filtered according to the type
