### ISSUE TITLE
Get url to precomputed chunks from the regions

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#9]
In the current approach, in the regions, we have key "ngId": "MNI152_V25_RIGHT_NG_SPLIT_HEMISPHERE" what we are using for the URL to precomputed chunks
Is it possible to get the MNI152_V25_RIGHT_NG_SPLIT_HEMISPHERE keyword for the region from the Brainscapes api?

----------- old comments ---------
Gui, Xiaoyun

I should clarify:

We need a way to access URL endpoint for precomputed volume(s).

We also need a way to map region (e.g. hoc1 left hemisphere, v2.5) to precomputed url + label index.

Currently, this is done via ngId key and labelIndex key.

We will need to replicate this in brainscapes.

---
Dickscheid, Timo

I am working on bigbrain integration right now in the feature_bigbrainaccess branch. I will update you on this next week, it will make these things straightforward for the API.

**Comment by xgui3783** [comment]
depend on https://github.com/FZJ-INM1-BDA/siibra-python/issues/12

**Comment by xgui3783** [comment]
fixed by #14
